import { Avatar, Box, Container, Grid, Paper, Stack, ThemeProvider, Typography } from '@mui/material'
import type { NextPage } from 'next'
import Head from 'next/head'
import { Header } from '../components/header'
import { TextCard } from '../components/TextCard'
import styles from '../styles/Home.module.css'
import contents from '../contents/contents.json'
import { theme } from '../themes/Theme'
import { SectionTitle } from '../components/SectionTitle'

type WorksContent = {
  title: string,
  description: string,
  link: string,
  image: string,
  technology: string[]
}

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@300;400;500&display=swap" rel="stylesheet" />
      </Head>
      <ThemeProvider theme={theme}>
        <Header ></Header>

        <main className={styles.main}>
          <Container maxWidth="lg">
            <Box m={3}>
              <Avatar
                alt="Remy Sharp"
                src="/images/icon.png"
                sx={{ width: 200, height: 200, m: "auto" }}
              />
            </Box>

            <Typography variant='h1' sx={{ fontWeight: "bold", textAlign: "center" }}>
              Koki Sakai
            </Typography>
            <Typography variant='h5' sx={{ textAlign: "center", m: 2 }}>fumigoro / 文ゴロイド</Typography>
            <SectionTitle text="About" />
            <Typography gutterBottom>
              2000年愛知県生まれ、県内の普通科高校を卒業し、現在は岐阜大学工学部に在籍しています。
              高校時代に入部していた演劇部で「文ゴロイド」という奇抜なニックネームを先輩につけられ、今もこの名前を使っています。
              大学入学時に入った技術系サークルProg-Gにて刺激を受けプログラミングを始めました。
              「面倒な動作を解消する！」このへのモチベーションが高く、自分自身が日々感じてきた面倒な作業から開放してくれるコンテンツを中心に制作しています。
            </Typography>
            {/* <Typography gutterBottom>
              また、高校演劇部時代にイベントや興行を裏で支える人の存在を目にし、そういった仕事への憧れから大学入学時から学祭実行委員会（岐阜大学祭全学執行委員会）へ所属していました。
              3回生の時には執行委員長を努め、イベント開催が難しい情勢の中で2021年10月、「第73回岐阜大学祭～最初で最後！NEOnline祭～」と題し初のオンライン開催を達成しました。
            </Typography> */}

            <SectionTitle text="Works" />
            <Box sx={{ textAlign: "center", }}>
              {contents.works.map(works => (
                <TextCard src={works} />
              ))}
            </Box>

            <SectionTitle text="Activity" />
            <Box sx={{ textAlign: "center", }}>
              {contents.activity.map(activity => (
                <TextCard src={activity} />
              ))}
            </Box>
          </Container>
        </main>

        <footer className={styles.footer}>
          fumigoro
        </footer>
      </ThemeProvider>

    </>

  )
}

export default Home
