import { Avatar, Box, Container, Grid, Paper, Stack, Typography } from '@mui/material'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Header } from '../components/header'
import { TextCard } from '../components/TextCard'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header ></Header>

      <main className={styles.main}>
        <Container maxWidth="lg">
          <Avatar
            alt="Remy Sharp"
            src="/images/icon.png"
            sx={{ width: 200, height: 200, m: 2 }}
          />
          <h1 className={styles.title}>
            Koki Sakai
          </h1>
          <h2>fumigoro / 文ゴロイド</h2>
          <Typography gutterBottom>
            2000年愛知県生まれ、県内の普通科高校を卒業し、現在は岐阜大学工学部に在籍しています。
            高校時代に入部していた演劇部で「文ゴロイド」という奇抜なニックネームを先輩につけられ、今もこの名前を使っています。
            大学入学時に入った技術系サークルProg-Gにて刺激を受けプログラミングを始めました。
            「面倒な動作を解消する！」このへのモチベーションが高く、自分自身が日々感じてきた面倒な作業から開放してくれるコンテンツを中心に制作しています。
          </Typography>
          <Typography gutterBottom>
            また、高校演劇部時代にイベントや興行を裏で支える人の存在を目にし、そういった仕事への憧れから大学入学時から学祭実行委員会（岐阜大学祭全学執行委員会）へ所属していました。
            3回生の時には執行委員長を努め、イベント開催が難しい情勢の中で2021年10月、「第73回岐阜大学祭～最初で最後！NEOnline祭～」と題し初のオンライン開催を達成しました。
          </Typography>
          <Box>
            <Box sx={{ textAlign: "center" }}>
              <TextCard title="AIMS Gifu Extention" description='AIMS Gifuを便利にする拡張機能' />
              <TextCard title="Aims Gifu Extention" description='AIMS Gifuを便利にする拡張機能' />
              <TextCard title="Aims Gifu Extention" description='AIMS Gifuを便利にする拡張機能' />
              <TextCard title="Aims Gifu Extention" description='AIMS Gifuを便利にする拡張機能' />
            </Box>
          </Box>

        </Container>
      </main>

      <footer className={styles.footer}>
        fumigoro
      </footer>
    </>

  )
}

export default Home
